import = ["/home/anil/config/alacritty/themes/tokyo-night.yaml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.8

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
